name: Deploy Maksb

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build application
      run: |
        npm install
        npm run build


